# Generated by Django 3.2.4 on 2021-06-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacks',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
